{
 "title": "Printer",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "current print", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "state_id" ], "type": "tag" }
     ],
     "measurement": "prometheus_remote_write",
     "query": "SELECT \"octoprint_printer_state_info\" FROM \"autogen\".\"prometheus_remote_write\" WHERE $timeFilter GROUP BY \"state_id\"",
     "select": [
      [
       { "params": [ "octoprint_printer_state_info" ], "type": "field" },
       { "params": [ "1" ], "type": "top" }
      ]
     ]
    }
   ]
  },
  {
   "title": "printing time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "octoprint_print_time_elapsed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "extrusion",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "octoprint_extrusion_print" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fan",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "octoprint_print_fan_speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "general",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prints failed, prints done",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "prometheus_remote_write",
       "select": [
        [
         { "params": [ "octoprint_failed_prints_total" ], "type": "field" }
        ],
        [
         { "params": [ "octoprint_done_prints_total" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Temps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Bed temperatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "prometheus_remote_write",
     "query": "SELECT \"octoprint_temperatures_actual\", \"octoprint_temperatures_target\" FROM \"prometheus_remote_write\" WHERE (\"identifier\" = 'B') AND $timeFilter GROUP BY \"identifier\"",
     "select": [
      [
       { "params": [ "octoprint_temperatures_actual" ], "type": "field" }
      ],
      [
       { "params": [ "octoprint_temperatures_target" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=", "value": "B" }
     ]
    }
   ]
  },
  {
   "title": "Extruder temps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "prometheus_remote_write",
     "query": "SELECT \"octoprint_temperatures_actual\", \"octoprint_temperatures_target\" FROM \"prometheus_remote_write\" WHERE (\"identifier\" = 'B') AND $timeFilter GROUP BY \"identifier\"",
     "select": [
      [
       { "params": [ "octoprint_temperatures_actual" ], "type": "field" }
      ],
      [
       { "params": [ "octoprint_temperatures_target" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=", "value": "T0" }
     ]
    }
   ]
  },
  {
   "title": "Ringing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "avg acceleration measured",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "measurement": "prometheus_remote_write",
       "select": [
        [
         { "params": [ "printmon_acceleration_avg_x" ], "type": "field" }
        ],
        [
         { "params": [ "printmon_acceleration_avg_y" ], "type": "field" }
        ],
        [
         { "params": [ "printmon_acceleration_avg_z" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "max acceleration over last measurement batch",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "measurement": "prometheus_remote_write",
       "select": [
        [
         { "params": [ "printmon_acceleration_max_x" ], "type": "field" }
        ],
        [
         { "params": [ "printmon_acceleration_max_y" ], "type": "field" }
        ],
        [
         { "params": [ "printmon_acceleration_max_z" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Measurements",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "measurement": "prometheus_remote_write",
       "query": "SELECT \"printmon_samplecount\", \"printmon_ticktime\" FROM \"prometheus_remote_write\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "printmon_samplecount" ], "type": "field" }
        ],
        [
         { "params": [ "printmon_ticktime" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}