version: "3"

volumes:
  prometheus-storage:

services:
  gateway:
    privileged: true
    restart: always
    build: .
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: 
      - .env

  prometheus:
    image: prom/prometheus:v2.20.0
    restart: always
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - prometheus-storage:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  telegraf:
    image: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro